require_relative "test_helper"
require "tmpdir"
require "open3"

# The command line tool, run as it actually would be.
class TestCommand < Minitest::Test

  COMMAND = File.expand_path("../bin/carray-jit", __dir__)

  def setup
    @root = Dir.mktmpdir("carray-jit-command-")
  end

  def teardown
    FileUtils.remove_entry(@root) if File.directory?(@root)
  end

  def run_command (*arguments)
    output, status = Open3.capture2e({ "CARRAY_JIT_CACHE" => @root },
                                     RbConfig.ruby, COMMAND, *arguments)
    [output, status.exitstatus]
  end

  # Compiles in a child process, so the cache is populated the same way a
  # real program would leave it.
  def populate (count = 2)
    script = <<~RUBY
      $LOAD_PATH.unshift(#{File.expand_path('../lib', __dir__).inspect})
      require "carray/jit"
      #{count}.times do |index|
        CArray::JIT.compile("->(i) { a[i] = a[i-1] * \#{index}.5 }",
                            array_names: [:a],
                            storage_types: { :a => "float64" },
                            scalar_values: {})
      end
    RUBY
    output, status = Open3.capture2e({ "CARRAY_JIT_CACHE" => @root },
                                     RbConfig.ruby, "-e", script)
    assert(status.success?, "could not populate the cache: #{output}")
  end

  def test_status_reports_an_empty_cache
    output, code = run_command("status")
    assert_equal(0, code)
    assert_match(/root\s+#{Regexp.escape(@root)}/, output)
    assert_match(/kernels\s+0/, output)
  end

  def test_status_is_the_default_command
    assert_equal(run_command("status").first, run_command.first)
  end

  def test_status_counts_cached_kernels
    populate(2)
    output, code = run_command("status")
    assert_equal(0, code)
    assert_match(/kernels\s+2/, output)
    assert_match(/environment\s+#{Regexp.escape(CArray::JIT::VERSION)}-/, output)
  end

  # A hash says nothing about which kernel it is; where it was written does.
  def test_list_shows_where_the_kernel_came_from
    script = File.join(@root, "kernel_script.rb")
    File.write(script, <<~RUBY)
      $LOAD_PATH.unshift(#{File.expand_path('../lib', __dir__).inspect})
      require "carray/jit"
      values = CArray.double(8).seq!(1.0)
      CArray.jit_for(1...8) { |i|
        values[i] = values[i-1] * 2.0
      }
    RUBY
    _output, status = Open3.capture2e({ "CARRAY_JIT_CACHE" => @root },
                                      RbConfig.ruby, script)
    assert(status.success?)

    output, code = run_command("list")
    assert_equal(0, code)
    assert_match(/#{Regexp.escape(script)}:4/, output)
  end

  # A kernel compiled from a source string has no file behind it, so the block
  # itself stands in for one.
  def test_list_falls_back_to_the_source_text
    populate(1)
    output, code = run_command("list")
    assert_equal(0, code)
    assert_match(/->\(i\) \{ a\[i\] = a\[i-1\]/, output)
  end

  def test_show_prints_where_the_kernel_came_from
    populate(1)
    listing, = run_command("list")
    key = listing.split.first
    output, code = run_command("show", key)
    assert_equal(0, code)
    assert_match(/Generated by carray-jit/, output)
    assert_match(/a\[i\] = a\[i-1\]/, output)
  end

  def test_list_on_an_empty_cache
    output, code = run_command("list")
    assert_equal(0, code)
    assert_match(/no kernels cached/, output)
  end

  def test_show_prints_the_c_source
    populate(1)
    key = run_command("list").first.split.first
    output, code = run_command("show", key)
    assert_equal(0, code)
    assert_match(/#include <stdint.h>/, output)
    assert_match(/for \(int64_t i = /, output)
  end

  def test_show_reports_an_unknown_key
    output, code = run_command("show", "nosuchkernel")
    assert_equal(1, code)
    assert_match(/no cached kernel starts with/, output)
  end

  def test_show_without_a_key_is_an_error
    output, code = run_command("show")
    assert_equal(1, code)
    assert_match(/needs the start of a kernel's key/, output)
  end

  def test_clear_empties_this_environment
    populate(2)
    output, code = run_command("clear")
    assert_equal(0, code)
    assert_match(/removed 2 kernels/, output)
    assert_match(/kernels\s+0/, run_command("status").first)
  end

  def test_clear_leaves_other_environments_alone
    populate(1)
    other = File.join(@root, "0.0.1-somewhere")
    FileUtils.mkdir_p(other)
    FileUtils.touch(File.join(other, "#{'0' * 64}.bundle"))

    run_command("clear")
    assert(File.directory?(other))
    assert_match(/other environments/, run_command("status").first)

    output, code = run_command("clear", "--all")
    assert_equal(0, code)
    refute(File.directory?(other))
  end

  def test_version_and_help
    output, code = run_command("--version")
    assert_equal(0, code)
    assert_equal(CArray::JIT::VERSION, output.strip)

    output, code = run_command("--help")
    assert_equal(0, code)
    assert_match(/Usage: carray-jit/, output)
  end

  def test_unknown_command_is_an_error
    output, code = run_command("bogus")
    assert_equal(1, code)
    assert_match(/Usage: carray-jit/, output)
  end

  # Inspecting the cache should not need CArray or the compiled extension.
  def test_runs_without_carray_loaded
    script = <<~RUBY
      $LOAD_PATH.unshift(#{File.expand_path('../lib', __dir__).inspect})
      load #{COMMAND.inspect} rescue nil
    RUBY
    output, = Open3.capture2e({ "CARRAY_JIT_CACHE" => @root },
                              RbConfig.ruby, "-e", script)
    refute_match(/cannot load such file.*carray/i, output)
  end

end
